_target_: amelia_tf.models.traj_pred_combined.CombinedTrajPredSystem

mode_optimizer:
  lr: 1e-4
  weight_decay: 1e-1
  beta1: 0.9
  beta2: 0.95

mode_scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: max
  factor: 0.1
  patience: 10

mode_net:
  _target_: amelia_tf.models.components.amelia_mode.AmeliaMode
  config:
    encoder:
      in_size: 4
      embed_size: 256
      interp_flag: ${data.dataset.config.encode_interp_flag}

      hist_len: ${data.dataset.config.hist_len}
      pred_lens: ${data.dataset.config.pred_lens}

      T_size: ${data.dataset.config.traj_len}
      A_size: ${data.dataset.config.k_agents}

      add_context: true
      context_encoder_type: 'v0'
      contextnet:
        in_size: 5
        embed_size: ${model.mode_net.config.encoder.embed_size}
        num_mlp_layers: 1
        num_satt_layers: 1
        num_heads: 8
        dropout: 0.0
        bias: True
        num_vectors: ${data.dataset.config.num_polylines}

      contextnet_v0:
        in_size: 5
        embed_size: ${model.mode_net.config.encoder.embed_size}
        num_layers: 2
        num_vectors: ${data.dataset.config.num_polylines}

      num_satt_pre_blocks: 1
      num_catt_pre_blocks: 1
      num_satt_blocks: 1
      num_catt_blocks: 1
      num_satt_post_blocks: 1

      num_layers: 5
      num_heads: 8
      dropout: 0.0
      bias: True

    mode_predictor:
      num_modes: 16
      hidden_dim: 256
      dropout: 0.1

traj_optimizer:
  lr: 1e-4
  weight_decay: 1e-1
  beta1: 0.9
  beta2: 0.95

traj_scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

traj_net:
  _target_: amelia_tf.models.components.amelia_trajectory.AmeliaTrajectory
  config:
    encoder:
      in_size: 4
      embed_size: 256
      interp_flag: ${data.dataset.config.encode_interp_flag}

      hist_len: ${data.dataset.config.hist_len}
      pred_lens: ${data.dataset.config.pred_lens}

      T_size: ${data.dataset.config.traj_len}
      A_size: ${data.dataset.config.k_agents}

      add_context: true
      context_encoder_type: 'v0'
      contextnet:
        in_size: 5
        embed_size: ${model.traj_net.config.encoder.embed_size}
        num_mlp_layers: 1
        num_satt_layers: 1
        num_heads: 8
        dropout: 0.0
        bias: True
        num_vectors: ${data.dataset.config.num_polylines}

      contextnet_v0:
        in_size: 5
        embed_size: ${model.traj_net.config.encoder.embed_size}
        num_layers: 2
        num_vectors: ${data.dataset.config.num_polylines}

      num_satt_pre_blocks: 1
      num_catt_pre_blocks: 1
      num_satt_blocks: 1
      num_catt_blocks: 1
      num_satt_post_blocks: 1

      num_layers: 5
      num_heads: 8
      dropout: 0.0
      bias: True

    decoder:
      num_modes: 4
      num_dims: 6
      num_futures: 1
      hidden_dim: 256
      num_decoder_layers: 4
      dropout: 0.1

extra_params:
  propagation: marginal
  tag: ${task_name}
  use_agent_masks: false

  seen_airports: ${data.extra_params.data_prep.seen_airports}
  unseen_airports: ${data.extra_params.data_prep.unseen_airports}

  asset_dir: ${paths.assets_dir}
  plot_dir: ${paths.vis_dir}
  plot_train: False
  plot_val: False
  plot_test: False
  plot_every_n: 10
  plot_after_n_epochs: 20
  alpha_score_ce:  0      
  alpha_score_ade: 1.0      